spring.application.name=backend
server.port=8081
# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5433/sanfast_db
spring.datasource.username=root
spring.datasource.password=rootpassword

# JPA Configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Kafka Producer Configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Gemini AI Configuration
gemini.api.key=AIzaSyBmXk9VzUH76IFiPfsIBWCFvl7JwCIczQU
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent
