server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5433/sanfast_db
spring.datasource.username=root
spring.datasource.password=rootpassword
spring.jpa.hibernate.ddl-auto=update

# Redis Caching
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis

# AI Gemini Config (Please fill in the real keys)
gemini.api.key=REPLACEME_WITH_YOUR_GEMINI_KEY
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent
